import { EnchantmentType } from "types/graphql";

export default [
  EnchantmentType.BonusStrength,
  EnchantmentType.BonusDexterity,
  EnchantmentType.BonusConstitution,
  EnchantmentType.BonusIntelligence,
  EnchantmentType.BonusWisdom,
  EnchantmentType.BonusWillpower,
  EnchantmentType.BonusLuck,
  EnchantmentType.BonusPhysical,
  EnchantmentType.BonusMental,
  EnchantmentType.BonusAllStats,
  EnchantmentType.MinusEnemyArmor,
  EnchantmentType.BonusArmor,
  EnchantmentType.MinusEnemyStrength,
  EnchantmentType.MinusEnemyDexterity,
  EnchantmentType.MinusEnemyConstitution,
  EnchantmentType.MinusEnemyIntelligence,
  EnchantmentType.MinusEnemyWisdom,
  EnchantmentType.MinusEnemyWillpower,
  EnchantmentType.MinusEnemyPhysical,
  EnchantmentType.MinusEnemyMental,
  EnchantmentType.MinusEnemyAllStats,
  EnchantmentType.BigMelee,
  EnchantmentType.BigCaster,
  EnchantmentType.FishermansStrength,
  EnchantmentType.FishermansDexterity,
  EnchantmentType.FishermansConstitution,
  EnchantmentType.FishermansIntelligence,
  EnchantmentType.FishermansWisdom,
  EnchantmentType.FishermansWillpower,
  EnchantmentType.FishermansLuck,

  // damaging / healing
  EnchantmentType.StrengthSteal,
  EnchantmentType.DexteritySteal,
  EnchantmentType.ConstitutionSteal,
  EnchantmentType.IntelligenceSteal,
  EnchantmentType.WisdomSteal,
  EnchantmentType.WillpowerSteal,
  EnchantmentType.LuckSteal,
  EnchantmentType.AllStatsSteal,
  EnchantmentType.LifeSteal,
  EnchantmentType.LifeHeal,
  EnchantmentType.LifeDamage,
  EnchantmentType.Vampirism,
];
